### ISSUE TITLE
Scribus beta instead of stable

### ISSUE THREAD

**Issue by jvnknvlgl** [flathub/net.scribus.Scribus#12]
Is there any reason why Flatpak hosts the beta version of Scribus instead of stable? It would be nice if there was any indication that this is the case.

**Comment by jurf** [comment]
For the simple reason that 1.4.x is now really old, while 1.5.x is nearly stable. As soon as 1.6 is released, this package will jump to stable and stay there. It was meant to be a temporary measure, but I’ve been waiting for 1.6 around 6 years now, which is much more than I originally anticipated.

As for indications, there’s a ‘beta’ tag and we modify the desktop file to have a ‘(Beta)’ suffix. As mentioned, this was supposed to be a temporary measure, but yeah, 1.5.5 is IMHO stable enough for it to not matter anymore too much.
