### ISSUE TITLE
sub-submenu rolled out from Insert is empty 

### ISSUE THREAD

**Issue by antistress** [flathub/net.scribus.Scribus#14]
Hi,

I've just installed latest net.scribus.Scribus from FlatHub and note that it's the 1st time I launch Scribus

In french, menu Insérer > Forme > "Formes par défaut" is empty.
Item can be selected and you can click on it but there is no label.

Same for other entries below "Formes par défaut" ("Flèches", "Organigramme", "Casse-tête" and "Caractères spéciaux"

Thanks

Screenshot :
![Capture d’écran de 2020-04-12 13-14-07](https://user-images.githubusercontent.com/2436957/79070387-0a370180-7cc5-11ea-9cb9-1a770e7de9bf.png)

**Comment by jurf** [comment]
If I understand correctly, you are talking about the ‘Shapes’ menu. My guess this is an issue with the Adwaita theme.

![image](https://user-images.githubusercontent.com/7472425/79070663-a10cb980-7cd7-11ea-84f1-88772deda04c.png)

**Comment by jurf** [comment]
Indeed, can reproduce with Adwaita but not with Fusion. Please file a bug here: https://github.com/FedoraQt/adwaita-qt

**Comment by antistress** [comment]
Thanks !

**Comment by antistress** [comment]
Bug has been fixed upstream, only need to wait for a release
