### ISSUE TITLE
Can't print from Scribus : only "File" is suggested

### ISSUE THREAD

**Issue by antistress** [flathub/net.scribus.Scribus#15]
Hi,

I've just installed latest net.scribus.Scribus from FlatHub and note that it's the 1st time I launch Scribus.

I tried to print my work but I only could save it into a ps file, ready to be print outside Scribus.

Note that for instance org.libreoffice.LibreOffice allow me to print directly

Thanks

Screenshot :
![Capture d’écran de 2020-04-12 16-04-12](https://user-images.githubusercontent.com/2436957/79070661-da88f900-7cc6-11ea-8c15-738bb69a25cf.png)

**Comment by jurf** [comment]
Sadly this is an upstream issue; Scribus doesn’t support the printing portal, so I doubt we can get this working here. You can always save a PDF and print that.

**Comment by antistress** [comment]
Thanks.

See https://github.com/scribusproject/scribus/issues/126

**Comment by antistress** [comment]
> i see that @jurf replied in the other ticket: of course, if flatpak needs to communicate with a portal, it's probably up to somebody from the flatpak community (or using flatpak) to come up with a patch.

(from [ale rimoldi ](https://github.com/aoloe))

**Comment by eszlari** [comment]
In PR https://github.com/flathub/net.scribus.Scribus/pull/16, I...

1. added --socket=cups (https://github.com/flatpak/flatpak/pull/3279)
2. updated the runtime to 5.14
3. updated the app to the most recent SVN revision

Unfortunately, this still not makes this work (tested under Kubuntu 20.04 with flatpak 1.6.3).

Maybe  @grulja has an idea.

**Comment by grulja** [comment]
I think I found the reason, we have "--no-cups" option used when building qtbase. I will fix it on our side.

**Comment by grulja** [comment]
Update the runtime, it should work now. I was able to see printers in Scribus and also in Kate.

**Comment by aoloe** [comment]
perfect, thanks!

**Comment by antistress** [comment]
I got Qt runtimes updates sooner, but still no printer for me.
Thanks

**Comment by grulja** [comment]
> I got Qt runtimes updates sooner, but still no printer for me.
> Thanks

Do you have Flatpak 1.6.x? The `--socket=cups` is not supported in older releases.

**Comment by antistress** [comment]
$ dpkg -s flatpak | grep ^Version
Version: 1.6.3-1

**Comment by antistress** [comment]
FWIW I've just uninstalled and then reinstalled Flatpak Scribus and bug is still there

**Comment by grulja** [comment]
I think the build of Scribus with the cups socket enabled hasn't been pushed to updates yet, you can find it here https://flathub.org/builds/#/builders/32/builds/18469, where you can download with the command below.

**Comment by antistress** [comment]
I think I'll be more comfortable to wait for next update since I"m not sure what will be the consequences of this regarding my current net.scribus.Scribus version and next updates
Thanks, I'll let you know

**Comment by grulja** [comment]
> I think I'll be more comfortable to wait for next update since I"m not sure what will be the consequences of this regarding my current net.scribus.Scribus version and next updates
> Thanks, I'll let you know

The build will go into updates in few hours so you should be able to test it later today.

**Comment by jurf** [comment]
I just published the build, it should be up in a matter of minutes.

@antistress regarding installing the testing version, a simple `flatpak uninstall net.scribus.Scribus//test` would suffice to revert the changes.

**Comment by antistress** [comment]
Bug is solved for me : I can now see my printer !
Thanks :)
