### ISSUE TITLE
Not sure if it linked Scribus make gnome-shell crash

### ISSUE THREAD

**Issue by yodatak** [flathub/net.scribus.Scribus#23]
Hi scribus is unusable and make gnome-shell restart when runing scribus. im not sure if its linked but i want to report it 
I don't know if its scribus or some issue with fedora 
Gnome shell : 3.38.1-1.fc33.x86_64
Scribus	net.scribus.Scribus	1.5.6.svn	stable	flathub	system

Its on Fedora 33 , i don't know how to debug the flatpak but i want to help !

**Comment by jurf** [comment]
Fedora 32, cannot reproduce this. In any way, no application should make gnome-shell crash. I’d open a bug on their end.

**Comment by hfiguiere** [comment]
works find on Fedora 34 (GNOME)
