### ISSUE TITLE
Abnormal behaviour click-selecting object lines

### ISSUE THREAD

**Issue by riveravaldez** [flathub/net.scribus.Scribus#25]
Hi, I've found this issue in Debian testing package: `1.5.5+svn23928+dfsg-1+b2 amd64` and that was the reason I tried flathub version. Bug is reported there also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972534

The problem appears to consist in some kind of amplified area of click-selection for some lines (object), so instead of selecting a line by clicking more or less precisely over it, a click in a blank region of page (even some other page) results in a non-clicked line being selected.

This happens with:

```
$ flatpak info net.scribus.Scribus 

Scribus - Open Source Page Layout and Desktop Publishing (DTP)

          ID: net.scribus.Scribus
  Referencia: app/net.scribus.Scribus/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Version: 1.5.6.svn
     License: GPL-2.0+
      Origen: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 237,2 MB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: e993a0cce35338bb89524777ae8cf74d9c08f2ddf737e955f27348d6d698f188
      Parent: 9fbda4095fde9bca78be078e743c76b4c87e4bcfd4a554aa42c8555a8e157437
     Subject: scribus: update svn rev (85a5943b)
        Date: 2020-10-09 20:38:35 +0000
```

Problem doesn't manifest, for instance, in the actual AppImage offered from Scribus website:

https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.5/

Let me know if I can provide any useful information.

Thanks a lot!

**Comment by aoloe** [comment]
hi @riveravaldez can you please thest the current appimage to see if the bug is still there?

https://gitlab.com/scribus/scribus/-/jobs/artifacts/master/raw/Scribus-nightly-x86_64.AppImage?job=appimage%3Alinux

ciao
a.l.e

**Comment by aoloe** [comment]
this is now filled upstream and seems to depend on high screen monitors rather than flatpak or appimages https://bugs.scribus.net/view.php?id=16304

**Comment by jurf** [comment]
Cool, I’ll keep this open so we can bump the git commit once it’s fixed.

**Comment by aoloe** [comment]
it was a double vs int issue.
it's fixed in the current code.
