### ISSUE TITLE
org.kde.Platform 5.15-22.08 available

### ISSUE THREAD

**Issue by ozeszty** [flathub/net.scribus.Scribus#41]
Currently Scribus uses org.kde.Platform 5.15-21.08 runtime which depends on older mesa (org.freedesktop.Platform.GL.default 21.3.9) while newer ones are available (runtime 5.15-22.08 and mesa 22.3.2).

**Comment by hfiguiere** [comment]
How is this a problem?

**Comment by ozeszty** [comment]
Thanks for the update.
Sorry I forgot about it, I've had an issue with other flatpak app using (buggy) mesa from older runtime event though it was built with newer one.
