### ISSUE TITLE
Possibility to add a development build for Scribus 1.7.0svn ?

### ISSUE THREAD

**Issue by luzpaz** [flathub/net.scribus.Scribus#61]
Hi @hfiguiere, thanks so much for this flatpak!  

### Ask

Is it possible to add a dev build to track 1.7.0svn ? 

### Reasoning

Currently there are no functioning quick "binary"-like solutions to run the dev build (AppImage isn't working). Building Scribus 1.7.0svn from source is painful on an older machine as well. So this means that 1.7.0 isn't being tested enough by the community, which is a shame because @nitramr's indigo UI/UX changes are being ported to it. A huge leap forward.

* Scribus AUR package page [1]
* Scribus AUR PKGBUILD for 1.7.0svn [2]

Thanks in advance for the consideration.

[1] https://aur.archlinux.org/packages/scribus-svn
[2] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=scribus-svn

**Comment by hfiguiere** [comment]
> Is it possible to add a dev build to track 1.7.0svn ?

No.

Flathub is not to host nightly builds.

**Comment by luzpaz** [comment]
ooof, that felt harsh. OK...thanks
