### ISSUE TITLE
Mount colour profiles from host

### ISSUE THREAD

**Issue by devurandom** [flathub/net.scribus.Scribus#7]
It would be very helpful if the colour profiles of the host (`/usr/share/color` and `~/.local/share/color`) were mounted in the appropriate locations inside the container, so that I could use the same colour profiles that were already set up for my system and printers on the host.

**Comment by devurandom** [comment]
There is a feature request already: flatpak/flatpak#1697

Nothing did so far come out of it, though. If the application runtime had a (possibly empty) directory `/usr/share/color`, it would be possible workaround the problem by mounting the host's directory into the container. However, the application runtime used by the Scribus Flatpak (org.kde.Platform/x86_64/5.11) does not contain this directory.

**Comment by jurf** [comment]
I’ll close this in favour of the upstream one, there’s nothing we can really do down here without horrible hacks.

**Comment by alexb3d** [comment]
The default route in Flatpak is `/run/host/usr/share/color/icc/`

**Comment by alexb3d** [comment]
Apparently, the only relegate in this task has been darktable.
